import http from './http'

export default {
  listarMaestros() { return http.get('/admin/maestros') },
  crearMaestro(datos) { return http.post('/admin/maestros', datos) },
  toggleMaestro(id, activo) { return http.patch(`/admin/maestros/${id}`, { activo }) },
  listarPadres(params) { return http.get('/admin/padres', { params }) },
  obtenerPadre(id) { return http.get(`/admin/padres/${id}`) },
  crearPadre(datos) { return http.post('/admin/padres', datos) },
  actualizarPadre(id, datos) { return http.patch(`/admin/padres/${id}`, datos) },
  eliminarPadre(id) { return http.delete(`/admin/padres/${id}`) },
  listarEstudiantes(params) { return http.get('/admin/estudiantes', { params }) },
  crearEstudiante(datos) { return http.post('/admin/estudiantes', datos) },
  actualizarEstudiante(id, datos) { return http.patch(`/admin/estudiantes/${id}`, datos) },
  listarGrados() { return http.get('/admin/grados') },
  listarMatriculas(params) { return http.get('/admin/matriculas', { params }) },
  obtenerMatricula(id) { return http.get(`/admin/matriculas/${id}`) },
  crearMatricula(datos) { return http.post('/admin/matriculas', datos) },
  actualizarMatricula(id, datos) { return http.patch(`/admin/matriculas/${id}`, datos) },
  eliminarMatricula(id) { return http.delete(`/admin/matriculas/${id}`) },
  registrarFamilia(datos) { return http.post('/admin/familias', datos) },
  crearAsignacion(datos) { return http.post('/admin/asignaciones', datos) },
  eliminarAsignacion(id) { return http.delete(`/admin/asignaciones/${id}`) },
  promocionIndividual(datos) { return http.post('/admin/promocion/individual', datos) },
  promocionGrado(datos) { return http.post('/admin/promocion/grado', datos) },
}
